server:
  port: 8081
spring:
  application:
    name: api-gateway
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/universitymanagementrealm
      client:
        registration:
          keycloak:
            client-id: university_client
            client-secret: CCLqRQlTzSOWbLxWs7NG83XhEatwTWQK
            scope: openid,profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/swagger-ui/oauth2-redirect.html"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/universitymanagementrealm
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: auth-docs
          uri: http://localhost:8082
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth,/v3/api-docs
        - id: student-service
          uri: http://localhost:8083
          predicates:
            - Path=/student/**
          filters:
            - TokenRelay
        - id: student-docs
          uri: http://localhost:8083
          predicates:
            - Path=/v3/api-docs/student
          filters:
            - RewritePath=/v3/api-docs/student,/v3/api-docs
        - id: faculty-service
          uri: http://localhost:8084
          predicates:
            - Path=/faculty/**
          filters:
            - TokenRelay
        - id: faculty-docs
          uri: http://localhost:8084
          predicates:
            - Path=/v3/api-docs/faculty
          filters:
            - RewritePath=/v3/api-docs/faculty,/v3/api-docs
        - id: department-service
          uri: http://localhost:8086
          predicates:
            - Path=/department/**
          filters:
            - TokenRelay
        - id: department-docs
          uri: http://localhost:8086
          predicates:
            - Path=/v3/api-docs/department
          filters:
            - RewritePath=/v3/api-docs/department,/v3/api-docs
        - id: grade-service
          uri: http://localhost:8094
          predicates:
            - Path=/grade/**
          filters:
            - TokenRelay
        - id: grade-docs
          uri: http://localhost:8094
          predicates:
            - Path=/v3/api-docs/grade
          filters:
            - RewritePath=/v3/api-docs/grade,/v3/api-docs
        - id: analyticsreport-service
          uri: http://localhost:8099
          predicates:
            - Path=/analytics/**
          filters:
            - TokenRelay
        - id: analyticsreport-docs
          uri: http://localhost:8099
          predicates:
            - Path=/v3/api-docs/analytics
          filters:
            - RewritePath=/v3/api-docs/analytics,/v3/api-docs
        - id: Attendance-service
          uri: http://localhost:8087
          predicates:
            - Path=/attendance/**
          filters:
            - TokenRelay
        - id: Attendance-docs
          uri: http://localhost:8087
          predicates:
            - Path=/v3/api-docs/attendance
          filters:
            - RewritePath=/v3/api-docs/attendance,/v3/api-docs
        - id: course-service
          uri: http://localhost:8098
          predicates:
            - Path=/course/**
          filters:
            - TokenRelay
        - id: course-docs
          uri: http://localhost:8098
          predicates:
            - Path=/v3/api-docs/course
          filters:
            - RewritePath=/v3/api-docs/course,/v3/api-docs
        - id: enrollment-service
          uri: http://localhost:8092
          predicates:
            - Path=/enrollments/**
          filters:
            - TokenRelay
        - id: enrollment-docs
          uri: http://localhost:8092
          predicates:
            - Path=/v3/api-docs/enrollments
          filters:
            - RewritePath=/v3/api-docs/enrollments,/v3/api-docs
        - id: exam-service
          uri: http://localhost:8096
          predicates:
            - Path=/exam/**
          filters:
            - TokenRelay
        - id: exam-docs
          uri: http://localhost:8096
          predicates:
            - Path=/v3/api-docs/exam
          filters:
            - RewritePath=/v3/api-docs/exam,/v3/api-docs
        - id: feemanagement-service
          uri: http://localhost:8095
          predicates:
            - Path=/fees/**
          filters:
            - TokenRelay
        - id: feemanagement-docs
          uri: http://localhost:8095
          predicates:
            - Path=/v3/api-docs/fees
          filters:
            - RewritePath=/v3/api-docs/fees,/v3/api-docs
        - id: Hostel-service
          uri: http://localhost:8093
          predicates:
            - Path=/hostel/**
          filters:
            - TokenRelay
        - id: Hostel-docs
          uri: http://localhost:8093
          predicates:
            - Path=/v3/api-docs/hostel
          filters:
            - RewritePath=/v3/api-docs/hostel,/v3/api-docs
        - id: library-service
          uri: http://localhost:8091
          predicates:
            - Path=/library/**
          filters:
            - TokenRelay
        - id: library-docs
          uri: http://localhost:8091
          predicates:
            - Path=/v3/api-docs/library
          filters:
            - RewritePath=/v3/api-docs/library,/v3/api-docs
        - id: notificationcommunication-service
          uri: http://localhost:8089
          predicates:
            - Path=/notification/**
          filters:
            - TokenRelay
        - id: notificationcommunication-docs
          uri: http://localhost:8089
          predicates:
            - Path=/v3/api-docs/notification
          filters:
            - RewritePath=/v3/api-docs/notification,/v3/api-docs
        - id: timetable-service
          uri: http://localhost:8097
          predicates:
            - Path=/timetable/**
          filters:
            - TokenRelay
        - id: timetable-docs
          uri: http://localhost:8097
          predicates:
            - Path=/v3/api-docs/timetable
          filters:
            - RewritePath=/v3/api-docs/timetable,/v3/api-docs

springdoc:
  swagger-ui:
    persist-authorization: true
    disable-swagger-default-url: true
    oauth:
      client-id: university_client
      client-secret: CCLqRQlTzSOWbLxWs7NG83XhEatwTWQK
      use-pkce-with-authorization-code-grant: true
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: student-service
        url: /v3/api-docs/student
      - name: faculty-service
        url: /v3/api-docs/faculty
      - name: department-service
        url: /v3/api-docs/department
      - name: Attendance-service
        url: /v3/api-docs/attendance
      - name: analytics-service
        url: /v3/api-docs/analytics
      - name: enrollment-service
        url: /v3/api-docs/enrollments
      - name: library-service
        url: /v3/api-docs/library
      - name: feemanagement-service
        url: /v3/api-docs/fees
      - name: course-service
        url: /v3/api-docs/course
      - name: grade-service
        url: /v3/api-docs/grade
      - name: timetable-service
        url: /v3/api-docs/timetable
      - name: Hostel-service
        url: /v3/api-docs/hostel
      - name: exam-service
        url: /v3/api-docs/exam


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics